
import { allWords } from "./dictionaries";


const words = [
    { word: 'I', pronunciation: 'ai', definition: 'Yo' },
    { word: 'You', pronunciation: 'iú', definition: 'Tú' },
    { word: 'He', pronunciation: 'ji', definition: 'Él' },
    { word: 'She', pronunciation: 'shi', definition: 'Ella' },
    { word: 'We', pronunciation: 'uí', definition: 'Nosotros' },
    { word: 'They', pronunciation: 'Dei', definition: 'Ellos' },
    { word: 'Them', pronunciation: 'dem', definition: 'Ellos' },
    { word: 'Him', pronunciation: 'jim', definition: 'A él' },
    { word: 'His', pronunciation: 'jis', definition: 'Su' },
    { word: 'Her', pronunciation: 'ger', definition: 'Su' },

    { word: 'About', pronunciation: 'abaut', definition: 'Acerca de' },
    { word: 'Advertisement', pronunciation: 'advertuaisment', definition: 'anuncio' },
    { word: 'Aerial', pronunciation: 'er-ial', definition: 'Aéreo' },
    { word: 'After', pronunciation: 'after', definition: 'Despues' },
    { word: 'Agile', pronunciation: 'ayol', definition: 'Ágil' },
    { word: 'A', pronunciation: 'a', definition: 'un - uno - una' },
    { word: 'An', pronunciation: 'an', definition: 'un - uno - una' },
    { word: 'And', pronunciation: '', definition: 'Y' },
    { word: 'Again', pronunciation: 'eguen', definition: 'Otra vez' },
    { word: 'Against', pronunciation: 'eguenst', definition: 'En contra' },
    { word: 'Agreement', pronunciation: 'agriment', definition: 'Acuerdo' },
    { word: 'Air', pronunciation: 'er', definition: 'Aire' },
    { word: 'Algorithm', pronunciation: 'algridem', definition: 'Algoritmo' },
    { word: 'All', pronunciation: 'oll', definition: 'Todo - todos' },
    { word: 'Allergy', pronunciation: 'aleryi', definition: 'Alergia' },
    { word: 'Also', pronunciation: 'olso', definition: 'También' },
    { word: 'Although', pronunciation: 'oldo', definition: 'Aunque' },
    { word: 'Always', pronunciation: 'olwis', definition: 'Siempre' },
    { word: 'America', pronunciation: 'america', definition: 'America' },
    { word: 'Ammunition', pronunciation: 'emiunichen', definition: 'Munición' },
    { word: 'Analgesic', pronunciation: 'enal-yisik', definition: 'Analgésico' },
    { word: 'Analysis', pronunciation: 'enalisis', definition: 'Análisis' },
    { word: 'Analytics', pronunciation: 'enalidiks', definition: 'Análitica' },
    { word: 'Animal', pronunciation: 'enemel', definition: 'Animal' },
    { word: 'Answer', pronunciation: 'enser', definition: 'Respuesta' },
    { word: 'Antiseptic', pronunciation: 'entiseptik', definition: 'Antiséptico' },
    { word: 'Any', pronunciation: 'eny', definition: 'Cualquier' },
    { word: 'Anyone', pronunciation: 'eni-uan', definition: 'Alguien' },
    { word: 'Anything', pronunciation: 'eniting', definition: 'Cualquier cosa' },
    { word: 'Anywhere', pronunciation: 'eniuer', definition: 'En cualquier lugar' },
    { word: 'Application', pronunciation: 'aplikeichon', definition: 'Aplicación - Solicitud' },
    { word: 'Are', pronunciation: 'ar', definition: 'Son' },
    { word: 'Arrow', pronunciation: 'arrou', definition: 'Flecha' },
    { word: 'Area', pronunciation: '', definition: 'Área' },
    { word: 'Artificial', pronunciation: 'arde-fishol', definition: 'Artificial' },
    { word: 'As', pronunciation: 'as', definition: 'Como' },
    { word: 'Abide', pronunciation: 'abaid', definition: 'cumplir' },
    { word: 'Aspect', pronunciation: 'aspect', definition: 'Aspecto' },
    { word: 'At', pronunciation: 'at', definition: 'En' },
    { word: 'Automation', pronunciation: 'oro-meichen', definition: 'Automatización' },
    { word: 'Avalanche', pronunciation: 'ava-lantsh', definition: 'Avalancha' },
    { word: 'Away', pronunciation: 'e-uey', definition: 'Lejos' },
    { word: 'Awake', pronunciation: 'a-ueik', definition: 'Despierto' },
    { word: 'Axe', pronunciation: 'aks', definition: 'Hacha' },
    { word: 'Among', pronunciation: 'amang', definition: 'Entre' },
    { word: 'Above', pronunciation: 'abov', definition: 'Arriba de' },
    { word: 'Address', pronunciation: 'adres', definition: 'Dirección' },

    { word: 'Backpack', pronunciation: 'bak-pak', definition: 'Mochila' },
    { word: 'Breakfast', pronunciation: '', definition: 'Desayuno' },
    { word: 'Backup', pronunciation: 'bak-up', definition: 'Respaldo' },
    { word: 'Bandage', pronunciation: 'bendich', definition: 'Vendaje' },
    { word: 'Bread', pronunciation: 'bred', definition: 'Pan' },
    { word: 'Boxing', pronunciation: 'boxing', definition: 'Boxeo' },
    { word: 'Box', pronunciation: 'box', definition: 'Caja' },
    { word: 'Bear', pronunciation: 'ber', definition: 'Oso' },
    { word: 'Because', pronunciation: 'bicos', definition: 'Porque' },
    { word: 'Before', pronunciation: 'befor', definition: 'antes' },
    { word: 'Between', pronunciation: 'be-tuin', definition: 'Entre' },
    { word: 'Big', pronunciation: 'big', definition: 'Grande' },
    { word: 'Binoculars', pronunciation: 'banakiulers', definition: 'Binoculares' },
    { word: 'Bow', pronunciation: 'bou', definition: 'Arco' },
    { word: 'Boots', pronunciation: 'buts', definition: 'Botas' },
    { word: 'Book', pronunciation: 'buk', definition: 'Libro' },
    { word: 'Bottle', pronunciation: '', definition: 'Botella' },
    { word: 'Budget', pronunciation: 'bayet', definition: 'Presupuesto' },
    { word: 'Bug net', pronunciation: 'bag-net', definition: 'Toldillo' },
    { word: 'But', pronunciation: 'bat', definition: 'Pero' },
    { word: 'By', pronunciation: 'bay', definition: 'Por - Mediante - Según - Junto a' },
    { word: 'Below', pronunciation: 'below', definition: 'Abajo' },
    { word: 'Branch', pronunciation: 'branch', definition: 'Rama' },

    { word: 'Camera', pronunciation: '', definition: 'Cámara' },
    { word: 'Campfire', pronunciation: 'camp-faier', definition: 'Hoguera - Fogata' },
    { word: 'Card', pronunciation: 'card', definition: 'Tarjeta' },
    { word: 'Certain', pronunciation: 'cert-en', definition: 'Cierto' },
    { word: 'Coffee', pronunciation: 'cofi', definition: 'Café' },
    { word: 'Chocolate', pronunciation: '', definition: 'Chocolate' },
    { word: 'Chicken', pronunciation: 'chiken', definition: 'Pollo' },
    { word: 'Canyon', pronunciation: 'kanien', definition: 'Cañón' },
    { word: 'Car', pronunciation: 'car', definition: 'Carro' },
    { word: 'Carabiner', pronunciation: 'karabiner', definition: 'Mosquetón' },
    { word: 'characteristic', pronunciation: '', definition: 'Caracterìstica' },
    { word: 'Cartographer', pronunciation: 'kartagrefer', definition: 'Cartógrafo' },
    { word: 'Cartography', pronunciation: 'kartagrefi', definition: 'Cartografía' },
    { word: 'Case', pronunciation: 'kes', definition: 'Caso' },
    { word: 'Charger', pronunciation: 'charyer', definition: 'Cargador' },
    { word: 'Center', pronunciation: 'center', definition: 'centro' },
    { word: 'Crew', pronunciation: 'kru', definition: 'Grupo - equipo' },
    { word: 'City', pronunciation: 'siti', definition: 'Ciudad' },
    { word: 'Cliff', pronunciation: 'klif', definition: 'Acantilado' },
    { word: 'Clothes', pronunciation: 'klotz', definition: 'Ropa' },
    { word: 'Cloud', pronunciation: 'kloud', definition: 'Nube' },
    { word: 'Code', pronunciation: 'koud', definition: 'Código' },
    { word: 'Collaboration', pronunciation: 'colaboreichen', definition: 'Colaboración' },
    { word: 'Company', pronunciation: 'campani', definition: 'Compañía' },
    { word: 'Compass', pronunciation: 'kampes', definition: 'Brújula' },
    { word: 'Computer', pronunciation: 'kampiurer', definition: 'Computador' },
    { word: 'Conferece', pronunciation: 'kanfrens', definition: 'Conferencia' },
    { word: 'Container', pronunciation: 'kenteiner', definition: 'Contenedor' },
    { word: 'Content', pronunciation: 'kanten', definition: 'Contenido' },
    { word: 'Contour', pronunciation: 'kan-tor', definition: 'Contorno' },
    { word: 'Coordinates', pronunciation: 'coordenets', definition: 'Coordenadas' },
    { word: 'Cost', pronunciation: 'cost', definition: 'Costo' },
    { word: 'Course', pronunciation: 'kors', definition: 'Curso' },
    { word: 'Cycle', pronunciation: 'saicol', definition: 'Ciclo' },

    { word: 'Dinner', pronunciation: 'diner', definition: 'Cena' },
    { word: 'Data', pronunciation: 'deira', definition: 'Datos' },
    { word: 'Database', pronunciation: 'dara-beis', definition: 'Base de datos' },
    { word: 'Datum', pronunciation: 'dadem', definition: 'Dato' },
    { word: 'Day', pronunciation: 'dey', definition: 'Día' },
    { word: 'Deal', pronunciation: 'dill', definition: 'Trato' },
    { word: 'Dehydration', pronunciation: 'dijai-dreichen', definition: 'Deshidratación' },
    { word: 'deployment', pronunciation: 'deploiment', definition: 'Despliegue' },
    { word: 'Desert', pronunciation: 'desert', definition: 'Desierto' },
    { word: 'Desk', pronunciation: 'desk', definition: 'Escritorio' },
    { word: 'Device', pronunciation: 'devais', definition: 'Dispositivo' },
    { word: 'Different', pronunciation: 'di-frent', definition: 'Diferente' },
    { word: 'Direction', pronunciation: '', definition: 'Dirección' },
    { word: 'Disaster', pronunciation: 'desaster', definition: 'Desastre' },
    { word: 'Down', pronunciation: 'daun', definition: 'Abajo' },
    { word: 'Declination', pronunciation: 'daclineichen', definition: 'Declinación' },


    { word: 'Earthquake', pronunciation: 'erz-cueic', definition: 'Terremoto' },
    { word: 'East', pronunciation: 'ist', definition: 'Este' },
    { word: 'Electronic', pronunciation: 'elek-tranik', definition: 'Electrónica' },
    { word: 'Elevation', pronunciation: 'eleveichen', definition: 'Elevación' },
    { word: 'Earth', pronunciation: 'Erz', definition: 'Arena' },
    { word: 'Email', pronunciation: 'imel', definition: 'Correo' },
    { word: 'Emergency', pronunciation: 'emerjensi', definition: 'Emergencia' },
    { word: 'Egg', pronunciation: 'eg', definition: 'Huevo' },
    { word: 'End', pronunciation: 'end', definition: 'Fin' },
    { word: 'Engine', pronunciation: 'enjen', definition: 'Motor' },
    { word: 'Early', pronunciation: 'erly', definition: 'Temprano' },
    { word: 'Every', pronunciation: 'ebri', definition: 'Cada' },
    { word: 'Even', pronunciation: 'iven', definition: 'Incluso' },
    { word: 'Event', pronunciation: 'event', definition: 'Evento' },
    { word: 'Eyes', pronunciation: 'ai', definition: 'Ojo' },

    { word: 'Fact', pronunciation: 'fakt', definition: 'Hecho' },
    { word: 'Far', pronunciation: 'far', definition: 'Lejos' },
    { word: 'Farm', pronunciation: 'farm', definition: 'Granja' },
    { word: 'Few', pronunciation: 'fiu', definition: 'Pocos' },
    { word: 'Feature', pronunciation: 'ficher', definition: 'caracterìstica' },
    { word: 'Fire', pronunciation: 'faier', definition: 'Fuego' },
    { word: 'Firewall', pronunciation: 'faier-wol', definition: 'Cortafuegos' },
    { word: 'First', pronunciation: 'ferst', definition: 'Primero' },
    { word: 'First aid', pronunciation: 'ferst-eid', definition: 'Primeros auxilios' },
    { word: 'First-aid kit', pronunciation: 'ferst-eid kit', definition: 'Kit de primeros auxilios' },
    { word: 'Fish', pronunciation: 'fich', definition: 'Pez' },
    { word: 'Fishing bait', pronunciation: 'fiching beit', definition: 'Cebo de pesca' },
    { word: 'Flares', pronunciation: 'flers', definition: 'Bengalas' },
    { word: 'Flashlight', pronunciation: 'flach-lait', definition: 'Linterna' },
    { word: 'Flood', pronunciation: 'flod', definition: 'Inundación' },
    { word: 'Food', pronunciation: 'fud', definition: 'Comida' },
    { word: 'For', pronunciation: 'for', definition: 'Por' },
    { word: 'Forage', pronunciation: 'for-ech', definition: 'Forraje' },
    { word: 'Forecast', pronunciation: 'for-kast', definition: 'Pronóstico' },
    { word: 'Four', pronunciation: 'for', definition: 'Cuatro' },
    { word: 'Friend', pronunciation: 'fren', definition: 'Amigo' },
    { word: 'From', pronunciation: 'from', definition: 'De - Desde' },
    { word: 'Food', pronunciation: 'Fud', definition: 'Comida' },
    { word: 'Family', pronunciation: 'femly', definition: 'Familia' },
    { word: 'Front', pronunciation: 'front', definition: 'Frente' },

    { word: 'Game', pronunciation: 'gueim', definition: 'Juego' },
    { word: 'Gear', pronunciation: 'guir', definition: 'Engranaje' },
    { word: 'Geographer', pronunciation: 'yia-grefer', definition: 'Geógrafo' },
    { word: 'Geographic', pronunciation: 'yio-grafic', definition: 'Gegráfico' },
    { word: 'Geography', pronunciation: 'yia-grefi', definition: 'Geografía' },
    { word: 'Geologic', pronunciation: 'yio-loyic', definition: 'Geológico' },
    { word: 'Geology', pronunciation: 'yia-leyi', definition: 'Geología' },
    { word: 'Ground', pronunciation: 'graund', definition: 'Suelo' },
    { word: 'Group', pronunciation: 'grup', definition: 'Grupo' },
    { word: 'Glasses', pronunciation: 'glases', definition: 'Gafas' },

    { word: 'Hammock', pronunciation: 'jamek', definition: 'Hamaca' },
    { word: 'Harbor', pronunciation: 'jarvor', definition: 'Puerto' },
    { word: 'Hard', pronunciation: 'jard', definition: 'Duro - Difícil' },
    { word: 'Hat', pronunciation: 'jat', definition: 'Sombrero' },
    { word: 'Headlamp', pronunciation: 'jed-lamp', definition: 'Linterna de cabeza' },
    { word: 'Hear', pronunciation: 'jir', definition: 'Aquí' },
    { word: 'Higt', pronunciation: 'jai', definition: 'Alto' },
    { word: 'Hike', pronunciation: 'jaik', definition: 'Caminata' },
    { word: 'Height', pronunciation: 'jait', definition: 'Altura' },
    { word: 'Harness', pronunciation: 'arnes', definition: 'Arnés' },
    { word: 'Hook', pronunciation: 'jok', definition: 'Gancho' },
    { word: 'Helmet', pronunciation: 'elmet', definition: 'Casco' },
    { word: 'Hill', pronunciation: 'jil', definition: 'Colina' },
    { word: 'Home', pronunciation: 'jom', definition: 'Hogar' },
    { word: 'House', pronunciation: 'jaus', definition: 'Casa' },
    { word: 'Hurricane', pronunciation: '', definition: 'Huracán' },
    { word: 'Hydration', pronunciation: 'jai-dreichen', definition: 'Hidratación' },
    { word: 'Hypothermia', pronunciation: 'jaipotermia', definition: 'Hipotermia' },

    { word: 'If', pronunciation: 'if', definition: 'si' },
    { word: 'Image', pronunciation: 'imech', definition: 'Imagen' },
    { word: 'In', pronunciation: 'in', definition: 'En' },
    { word: 'Incident', pronunciation: 'incident', definition: 'Incidente' },
    { word: 'Index', pronunciation: 'index', definition: 'Ídice' },
    { word: 'Information', pronunciation: 'infor-meichen', definition: 'Información' },
    { word: 'Infrastructure', pronunciation: 'infras-trakcher', definition: 'Infraestructura' },
    { word: 'Input', pronunciation: 'input', definition: 'Entrada - Aporte' },
    { word: 'Insects', pronunciation: 'insekt', definition: 'Insecto' },
    { word: 'Integration', pronunciation: 'inte-greichen', definition: 'Integración' },
    { word: 'Intelligence', pronunciation: 'in-teliyens', definition: 'Inteligencia' },
    { word: 'Interface', pronunciation: 'interfeis', definition: 'Interfaz' },
    { word: 'Interval', pronunciation: 'interval', definition: 'Intervalo' },
    { word: 'Into', pronunciation: 'intu', definition: 'En' },
    { word: 'Investment', pronunciation: 'investment', definition: 'Inversión' },
    { word: 'Is', pronunciation: 'is', definition: 'Es' },
    { word: 'Island', pronunciation: 'ailand', definition: 'Isla' },
    { word: 'It', pronunciation: 'it', definition: 'El' },

    { word: 'Just', pronunciation: 'yost', definition: 'Solo - Justo' },
    { word: 'Juice', pronunciation: '', definition: 'Jugo' },

    { word: 'Key', pronunciation: 'ki', definition: 'Llave' },
    { word: 'Keyboard', pronunciation: 'ki-bord', definition: 'Teclado' },
    { word: 'Kind', pronunciation: 'kaind', definition: 'Tipo - Amable' },
    { word: 'Kit', pronunciation: 'kit', definition: 'Equipo' },
    { word: 'Kookie', pronunciation: 'kuki', definition: 'Galleta' },
    { word: 'Knife', pronunciation: 'Naif', definition: 'Cuchillo' },

    { word: 'Lake', pronunciation: 'leik', definition: 'Lago' },
    { word: 'Land', pronunciation: 'land', definition: 'Tierra' },
    { word: 'Landmark', pronunciation: 'land-mark', definition: 'Punto de referencia' },
    { word: 'Lantern', pronunciation: 'lantern', definition: 'Linterna' },
    { word: 'Last', pronunciation: 'last', definition: 'Último' },
    { word: 'Latitude', pronunciation: 'latitud', definition: 'Latitud' },
    { word: 'Left', pronunciation: 'left', definition: 'Izquierda' },
    { word: 'Legend', pronunciation: 'leyend', definition: 'Leyenda' },
    { word: 'Letter', pronunciation: 'leder', definition: 'Carta - Letra' },
    { word: 'Level', pronunciation: 'level', definition: 'Nivel' },
    { word: 'Library', pronunciation: 'laibrery', definition: 'Biblioteca' },
    { word: 'Life', pronunciation: 'laif', definition: 'Vida' },
    { word: 'Little', pronunciation: '', definition: 'Pequeño - Poco' },
    { word: 'Load', pronunciation: 'loud', definition: 'Carga' },
    { word: 'Long', pronunciation: 'long', definition: 'largo' },
    { word: 'Longitude', pronunciation: 'lonyi-tud', definition: 'Longitud' },
    { word: 'Lowercase', pronunciation: 'louer-keis', definition: 'Minúscula' },
    { word: 'Late', pronunciation: 'leit', definition: 'Tarde' },
    { word: 'Lighter', pronunciation: 'lairer', definition: 'Encendedor' },
    { word: 'Line', pronunciation: 'lain', definition: 'Línea' },
    { word: 'Lunch', pronunciation: 'lanch', definition: 'Almuerzo' },
    { word: 'Lamp', pronunciation: 'lamp', definition: 'Lámpara' },

    { word: 'Machete', pronunciation: 'macheti', definition: 'Machete' },
    { word: 'Machine', pronunciation: 'ma-chin', definition: 'Máquina' },
    { word: 'Medication', pronunciation: 'medi-keichen', definition: 'Medicamento' },
    { word: 'Meat', pronunciation: 'mit', definition: 'Carne' },
    { word: 'Mistake', pronunciation: 'mesteik', definition: 'Error' },
    { word: 'Many', pronunciation: 'meni', definition: 'Muchos' },
    { word: 'Map', pronunciation: 'map', definition: 'Mapa' },
    { word: 'Medicine', pronunciation: 'medisin', definition: 'Medicamento' },
    { word: 'Meeting', pronunciation: 'miring', definition: 'Reunión' },
    { word: 'Men', pronunciation: 'men', definition: 'Hombres' },
    { word: 'Message', pronunciation: 'mesich', definition: 'Mensaje' },
    { word: 'Metrics', pronunciation: 'metriks', definition: 'Métrica' },
    { word: 'Microphone', pronunciation: 'maikre-fon', definition: 'Micrófono' },
    { word: 'Migration', pronunciation: 'mai-greichen', definition: 'Miración' },
    { word: 'Mind', pronunciation: 'maind', definition: 'Mente' },
    { word: 'Mirror', pronunciation: 'mirror', definition: 'Espejo' },
    { word: 'Mobile', pronunciation: '', definition: 'Móvil' },
    { word: 'Moment', pronunciation: 'moment', definition: 'Momento' },
    { word: 'Monitor', pronunciation: 'maneder', definition: 'Monitor' },
    { word: 'More', pronunciation: 'mor', definition: 'Más' },
    { word: 'Most', pronunciation: 'most', definition: 'Más' },
    { word: 'Mother', pronunciation: 'moder', definition: 'Mamá' },
    { word: 'Mountain', pronunciation: 'maun-ten', definition: '' },
    { word: 'Mouse', pronunciation: 'maus', definition: 'Ratón' },
    { word: 'Much', pronunciation: 'mach', definition: 'Mucho' },
    { word: 'My', pronunciation: 'may', definition: 'Mi' },

    { word: 'National', pronunciation: 'nashenal', definition: 'Nacional' },
    { word: 'Natural', pronunciation: '', definition: 'Natural' },
    { word: 'Nature', pronunciation: 'neicher', definition: 'Naturaleza' },
    { word: 'Navigation', pronunciation: 'navi-gueichen', definition: 'Navegación' },
    { word: 'Network', pronunciation: 'net-work', definition: 'Red' },
    { word: 'Never', pronunciation: 'never', definition: 'Nunca' },
    { word: 'New', pronunciation: 'niu', definition: 'Nuevo' },
    { word: 'Next', pronunciation: 'next', definition: 'Siguiente' },
    { word: 'Night', pronunciation: 'nait', definition: 'Noche' },
    { word: 'No', pronunciation: 'nou', definition: 'No' },
    { word: 'North', pronunciation: 'nort', definition: 'Norte' },
    { word: 'Northwest', pronunciation: 'nort-west', definition: 'Noroeste' },
    { word: 'Not', pronunciation: 'not', definition: 'No' },
    { word: 'Nothing', pronunciation: 'noting', definition: 'Nada' },
    { word: 'Now', pronunciation: 'nao', definition: 'Ahora' },
    { word: 'Number', pronunciation: 'namber', definition: 'Número' },

    { word: 'Of', pronunciation: 'of', definition: 'De' },
    { word: 'Off', pronunciation: 'of', definition: 'Apagado' },
    { word: 'Often', pronunciation: 'afen', definition: 'Con frecuencia' },
    { word: 'Oil', pronunciation: 'oil', definition: 'Aceite' },
    { word: 'Old', pronunciation: 'old', definition: 'Viejo' },
    { word: 'Once', pronunciation: 'uans', definition: 'Una vez - Alguna vez' },
    { word: 'One', pronunciation: 'uan', definition: 'Uno' },
    { word: 'Oneline', pronunciation: 'on-lain', definition: 'En línea' },
    { word: 'Only', pronunciation: 'only', definition: 'Solo' },
    { word: 'Or', pronunciation: 'or', definition: 'O' },
    { word: 'Orientation', pronunciation: 'orien-teichen', definition: 'Orientación' },
    { word: 'Other', pronunciation: 'oder', definition: 'Otro' },
    { word: 'Our', pronunciation: 'aur', definition: 'Nuestro' },
    { word: 'Out', pronunciation: 'aut', definition: 'Afuera' },
    { word: 'Output', pronunciation: 'aut-put', definition: 'Producción - Salida' },
    { word: 'Over', pronunciation: 'over', definition: 'Encima - Más de - Terminado' },
    { word: 'Own', pronunciation: 'oun', definition: 'Aceptar - Propio' },
    { word: 'On', pronunciation: 'an', definition: 'En' },
    { word: 'Orange', pronunciation: 'oranch', definition: 'Naranja' },

    { word: 'Page', pronunciation: 'pech', definition: 'Página' },
    { word: 'Pad', pronunciation: 'pad', definition: 'Colchoneta' },
    { word: 'Part', pronunciation: 'part', definition: 'Parte' },
    { word: 'Patch', pronunciation: 'pach', definition: 'Parche' },
    { word: 'Port', pronunciation: 'port', definition: 'Puerto' },
    { word: 'People', pronunciation: 'pipol', definition: 'Personas' },
    { word: 'Performance', pronunciation: 'per-formans', definition: 'Rendimiento' },
    { word: 'Peel', pronunciation: 'pil', definition: 'Rendimiento' },
    { word: 'Phone', pronunciation: 'fon', definition: 'Teléfono' },
    { word: 'Photography', pronunciation: 'fotagrefi', definition: 'Fotografía' },
    { word: 'physical', pronunciation: 'fisical', definition: 'Física' },
    { word: 'Physics', pronunciation: 'fisiks', definition: 'Física' },
    { word: 'Pill', pronunciation: 'pil', definition: 'Píldora' },
    { word: 'Pillow', pronunciation: '', definition: '' },
    { word: 'Place', pronunciation: 'pleis', definition: 'Lugar' },
    { word: 'Plane', pronunciation: 'plein', definition: 'Plano' },
    { word: 'Point', pronunciation: 'point', definition: 'Punto' },
    { word: 'Poisonous', pronunciation: 'poisenes', definition: 'Venenoso' },
    { word: 'Political', pronunciation: '', definition: 'Política' },
    { word: 'Politics', pronunciation: 'poli-tiks', definition: '' },
    { word: 'Politician', pronunciation: 'poli-tishen', definition: 'Político' },
    { word: 'Press', pronunciation: '', definition: 'Político' },
    { word: 'Printer', pronunciation: 'printer', definition: 'Impresora' },
    { word: 'Problem', pronunciation: 'prable', definition: 'Problema' },
    { word: 'Project', pronunciation: 'proyect', definition: 'Proyecto' },
    { word: 'Projection', pronunciation: 'proyec-shen', definition: 'Proyección' },
    { word: 'Protection', pronunciation: 'protec-shen', definition: 'Protección' },
    { word: 'Purifier', pronunciation: '', definition: 'Purificador' },

    { word: 'Question', pronunciation: 'cues-chen', definition: 'Pregunta' },

    { word: 'Radio', pronunciation: '', definition: 'Radio' },
    { word: 'Range', pronunciation: 'ruench', definition: 'Rango' },
    { word: 'Reach', pronunciation: 'ruich', definition: 'Alcanzar' },
    { word: 'Real', pronunciation: 'ruial', definition: 'Real' },
    { word: 'Reality', pronunciation: 'ruialidi', definition: 'Realidad' },
    { word: 'Recovery', pronunciation: '', definition: '' },
    { word: 'Recognition', pronunciation: 'recog-nichen', definition: 'Reconocimiento' },
    { word: 'Recognition', pronunciation: 're-kanesens', definition: 'Reconocimiento' },
    { word: 'Relief', pronunciation: 'relif', definition: 'Socorro - Relieve' },
    { word: 'Remote', pronunciation: 'remout', definition: 'Remoto' },
    { word: 'Response', pronunciation: 'ris-pans', definition: 'Respuesta' },
    { word: 'Repellent', pronunciation: 'ripelent', definition: 'Repelente' },
    { word: 'Rifle', pronunciation: 'ruai-fol', definition: 'Rifle' },
    { word: 'Right', pronunciation: 'rua-it', definition: 'Derecha - correcto - razon' },
    { word: 'River', pronunciation: 'ruiver', definition: 'Río' },
    { word: 'Rice', pronunciation: 'raiz', definition: 'Arroz' },
    { word: 'Road', pronunciation: 'roud', definition: 'Carretera - Camino' },
    { word: 'Robotics', pronunciation: 'rou-badiks', definition: 'Robótica' },
    { word: 'Rope', pronunciation: 'rop', definition: 'Soga' },
    { word: 'Route', pronunciation: 'rut', definition: 'Ruta' },

    { word: 'Security', pronunciation: 'rut', definition: 'Ruta' },
    { word: 'Same', pronunciation: 'seim', definition: 'Mismo' },
    { word: 'Satellite', pronunciation: '', definition: 'Satélite' },
    { word: 'Since', pronunciation: 'sens', definition: 'Desde' },
    { word: 'Scale', pronunciation: 'skel', definition: 'Escala' },
    { word: 'School', pronunciation: 'skul', definition: 'Escuela' },
    { word: 'Scissors', pronunciation: 'si-sors', definition: 'Tijeras' },
    { word: 'Sea', pronunciation: 'si', definition: 'Mar' },
    { word: 'Seabed', pronunciation: 'si-bed', definition: 'Fondo del mar' },
    { word: 'Security', pronunciation: 'se-kiuridi', definition: 'Seguridad' },
    { word: 'Server', pronunciation: 'server', definition: 'Servidor' },
    { word: 'Service', pronunciation: 'serves', definition: 'Servicio' },
    { word: 'Shelter', pronunciation: 'chelter', definition: 'Refugio - Albergue' },
    { word: 'Side', pronunciation: 'said', definition: 'Lado' },
    { word: 'Signal', pronunciation: 'signal', definition: 'Señal' },
    { word: 'Skill', pronunciation: 'skil', definition: 'Habilidad' },
    { word: 'Sleeping bag', pronunciation: 'sliping-bak', definition: 'Bolsa de dormir' },
    { word: 'Slope', pronunciation: 'slop', definition: 'Pendiente - Inclinación' },
    { word: 'Small', pronunciation: 'smol', definition: 'Pequeño' },
    { word: 'Snake', pronunciation: 'snek', definition: 'Serpiente' },
    { word: 'So', pronunciation: 'sou', definition: 'Entonces' },
    { word: 'Soda', pronunciation: 'soda', definition: 'Gaseosa' },
    { word: 'Some', pronunciation: 'som', definition: 'Alguno' },
    { word: 'Something', pronunciation: 'som-ting', definition: 'Algo' },
    { word: 'Sometimes', pronunciation: 'somtaims', definition: 'A veces' },
    { word: 'South', pronunciation: '', definition: 'Sur' },
    { word: 'Southeast', pronunciation: '', definition: 'Sureste' },
    { word: 'Southwest', pronunciation: '', definition: 'Sur oeste' },
    { word: 'Spell', pronunciation: 'spell', definition: 'Deletrear' },
    { word: 'State', pronunciation: 'steit', definition: 'Estado' },
    { word: 'Still', pronunciation: 'stell', definition: 'Aún' },
    { word: 'Storage', pronunciation: 'storech', definition: 'Almacenamiento' },
    { word: 'Storm', pronunciation: 'storm', definition: 'Tormenta' },
    { word: 'Story', pronunciation: 'stoty', definition: 'Historia' },
    { word: 'Stream', pronunciation: 'strim', definition: 'Corriente' },
    { word: 'Such', pronunciation: 'sach', definition: 'Semejante' },
    { word: 'Sun', pronunciation: 'son', definition: 'Sol' },
    { word: 'Shirt', pronunciation: 'shert', definition: 'Camisa' },
    { word: 'Sunscreen', pronunciation: 'sons-krin', definition: 'Protector solar' },
    { word: 'Survival', pronunciation: 'ser-vayvol', definition: 'Supervivencia' },
    { word: 'Survivor', pronunciation: 'ser-vaivor', definition: 'Sobreviviente' },
    { word: 'System', pronunciation: 'sistem', definition: 'Sistema' },
    { word: 'Shower', pronunciation: 'shouer', definition: 'Ducha' },

    { word: 'Tablet', pronunciation: 'tablet', definition: 'Tableta' },
    { word: 'Tent', pronunciation: 'tent', definition: 'Carpa' },
    { word: 'Time', pronunciation: 'Taim', definition: 'Tiempo' },
    { word: 'To', pronunciation: 'tu', definition: '' },
    { word: 'Trap', pronunciation: 'truap', definition: 'Trampa' },
    { word: 'Technology', pronunciation: 'tecnoloyi', definition: 'Tecnología' },
    { word: 'technique', pronunciation: 'tec-nic', definition: 'Técnica' },
    { word: 'Terrain', pronunciation: 'terren', definition: 'Terreno' },
    { word: 'Than', pronunciation: 'dan', definition: 'Que' },
    { word: 'That', pronunciation: 'dat', definition: 'Ese' },
    { word: 'The', pronunciation: 'de', definition: 'El - La - los - Las' },
    { word: 'Their', pronunciation: 'der', definition: 'Su' },
    { word: 'Then', pronunciation: 'den', definition: 'Entonces' },
    { word: 'There', pronunciation: 'der', definition: 'Allá' },
    { word: 'These', pronunciation: 'dis', definition: 'Estos' },
    { word: 'This', pronunciation: 'des', definition: 'Esto' },
    { word: 'Those', pronunciation: 'dous', definition: 'Aquellos' },
    { word: 'Thought', pronunciation: '', definition: 'Pensamiento' },
    { word: 'Three', pronunciation: '', definition: 'Tres' },
    { word: 'Through', pronunciation: 'tru', definition: 'A través de' },
    { word: 'Thunder', pronunciation: 'tander', definition: 'Trueno' },
    { word: 'Ticket', pronunciation: 'tiket', definition: 'Boleto' },
    { word: 'Tide', pronunciation: 'taid', definition: 'Marea' },
    { word: 'Time', pronunciation: 'taim', definition: 'Tiempo' },
    { word: 'Together', pronunciation: 'tu-gueder', definition: 'Juntos' },
    { word: 'Too', pronunciation: 'tu', definition: 'También' },
    { word: 'Tool', pronunciation: 'tul', definition: 'Herramientas' },
    { word: 'Top', pronunciation: 'tap', definition: 'Arriba' },
    { word: 'Topographic', pronunciation: 'tapografic', definition: 'Topográfico' },
    { word: 'Topography', pronunciation: 'te-pagrefi', definition: 'Topografía' },
    { word: 'Tornado', pronunciation: 'tor-neido', definition: 'Tornado' },
    { word: 'Treatment', pronunciation: 'truit-ment', definition: 'Tratamiento' },
    { word: 'Tree', pronunciation: '', definition: 'Árbol' },
    { word: 'Tweezers', pronunciation: 'tuisers', definition: 'Pinzas' },
    { word: 'Two', pronunciation: 'tu', definition: 'Dos' },
    { word: 'Train', pronunciation: 'trein', definition: 'Entrenar - Tren' },
    { word: 'Trouble', pronunciation: 'truabol', definition: 'Problemas' },

    { word: 'Us', pronunciation: 'os', definition: 'Nosotro' },
    { word: 'User', pronunciation: 'iuser', definition: 'Usuario' },
    { word: 'Until', pronunciation: 'antil', definition: 'Hasta' },
    { word: 'Unless', pronunciation: 'enles', definition: 'A menos que' },

    { word: 'Valley', pronunciation: 'vali', definition: 'Valle' },
    { word: 'Variation', pronunciation: '', definition: 'Variación' },
    { word: 'Vegetation', pronunciation: 'veye-teichen', definition: 'Vegetación' },
    { word: 'Venom', pronunciation: 'venom', definition: 'Veneno' },
    { word: 'Very', pronunciation: 'very', definition: 'Muy' },
    { word: 'Video', pronunciation: 'vidio', definition: 'Video' },
    { word: 'Volcano', pronunciation: 'volkeino', definition: 'Volcán' },
    { word: 'Vulnerability', pronunciation: '', definition: 'Vulnerabilidad' },
    { word: 'Vulnerable', pronunciation: '', definition: 'Vulnerable' },

    { word: 'Water', pronunciation: 'uarer', definition: 'Agua' },
    { word: 'Waterfall', pronunciation: 'uarer-fol', definition: 'Cascada' },
    { word: 'Way', pronunciation: 'uey', definition: 'Camino' },
    { word: 'Weather', pronunciation: 'ueder', definition: 'Clima' },
    { word: 'Website', pronunciation: 'ueb-sait', definition: 'Website' },
    { word: 'Well', pronunciation: 'uel', definition: 'Bien - Bueno' },
    { word: 'West', pronunciation: 'uest', definition: 'Oeste' },
    { word: 'Wetland', pronunciation: 'uet-land', definition: 'Humedal' },
    { word: 'What', pronunciation: 'uat', definition: 'Qué' },
    { word: 'When', pronunciation: 'uen', definition: 'Cuando' },
    { word: 'Where', pronunciation: 'uer', definition: 'Dónde' },
    { word: 'Which', pronunciation: 'uech', definition: 'Cual' },
    { word: 'While', pronunciation: 'uail', definition: 'Mientras' },
    { word: 'White', pronunciation: 'uait', definition: 'Blanco' },
    { word: 'Who', pronunciation: 'ju', definition: 'Quien' },
    { word: 'Wilderness', pronunciation: 'uildernes', definition: 'Desierto' },
    { word: 'With', pronunciation: 'uit', definition: 'Con' },
    { word: 'Within', pronunciation: 'uit-in', definition: 'Dentro' },
    { word: 'Without', pronunciation: 'uit-out', definition: 'Sin' },
    { word: 'World', pronunciation: 'uorld', definition: 'Mundo' },
    { word: 'Wave', pronunciation: 'ueiv', definition: 'Ola - Onda' },
    { word: 'Wound', pronunciation: 'wud', definition: 'Herida' },
    { word: 'Whether', pronunciation: 'ueder', definition: 'Si' },

    { word: 'Year', pronunciation: 'ier', definition: 'Año' },
    { word: 'Yet', pronunciation: 'yet', definition: 'Todavía' },
    { word: 'Your', pronunciation: 'iur', definition: 'Su' },

];
const regularVerbs = [
    { word: 'Accept', pronunciation: 'ak-sept', definition: 'Aceptar' },
    { word: 'Access', pronunciation: 'ak-ses', definition: 'Acceder - Acceso' },
    { word: 'Act', pronunciation: 'act', definition: 'Actuar, Acto' },
    { word: 'Add', pronunciation: 'ad', definition: 'Agregar' },
    { word: 'Admire', pronunciation: 'edmaier', definition: 'Admirar' },
    { word: 'Admire', pronunciation: 'edmaier', definition: 'Admirar' },
    { word: 'Admit', pronunciation: 'edmit', definition: 'Admitir' },
    { word: 'Advise', pronunciation: 'ed-vais', definition: 'Aconsejar' },
    { word: 'Agree', pronunciation: 'agri', definition: 'Aceptar - Acordar' },
    { word: 'Aim', pronunciation: 'eim', definition: 'Apuntar' },
    { word: 'Allow', pronunciation: 'alau', definition: 'Permitir' },
    { word: 'Analyze', pronunciation: 'enalais', definition: 'Analizar' },
    { word: 'Announce', pronunciation: 'anauns', definition: 'Anunciar' },
    { word: 'Answer', pronunciation: 'enser', definition: 'Responder - Respuesta' },
    { word: 'Appear', pronunciation: 'apir', definition: 'Aparecer' },
    { word: 'Apply', pronunciation: 'aplay', definition: 'Aplicar' },
    { word: 'Appreciate', pronunciation: 'aprishi-eit', definition: 'Agradecer' },
    { word: 'Approach', pronunciation: 'aproch', definition: 'Acercarse' },
    { word: 'Approve', pronunciation: 'apruv', definition: 'Aprobar' },
    { word: 'Argue', pronunciation: 'arruench', definition: 'Pactar - Planificar - Organizar' },
    { word: 'Arrive', pronunciation: '', definition: 'Llegar' },
    { word: 'Ask', pronunciation: 'ask', definition: 'Preguntar' },
    { word: 'Assess', pronunciation: 'ases', definition: 'Evaluar - Analizar' },
    { word: 'Assume', pronunciation: 'asum', definition: 'Asumir' },
    { word: 'Attach', pronunciation: 'atach', definition: 'Adjuntar - Añadir' },
    { word: 'Attack', pronunciation: 'atak', definition: 'Atacar - Ataque' },
    { word: 'Attend', pronunciation: 'atend', definition: 'Atender - Asistir' },
    { word: 'Attract', pronunciation: 'atract', definition: 'Atraer' },
    { word: 'Avoid', pronunciation: 'avoid', definition: 'Evitar' },

    { word: 'Back', pronunciation: 'bak', definition: 'Regresar - Atras' },
    { word: 'Base', pronunciation: 'beis', definition: 'Basar - Establecer' },
    { word: 'Belive', pronunciation: 'beliv', definition: 'Creer' },
    { word: 'Belong', pronunciation: 'belong', definition: 'Pertenecer' },
    { word: 'Blame', pronunciation: 'bleim', definition: 'Culpar - Responsabilidad' },
    { word: 'Block', pronunciation: 'blok', definition: 'Bloquear - Bloque ' },
    { word: 'Boil', pronunciation: 'boil', definition: 'Hervir' },
    { word: 'Borrow', pronunciation: '', definition: 'Pedir prestado' },
    { word: 'Bother', pronunciation: 'bader', definition: 'Molestar' },
    { word: 'Bounce', pronunciation: 'bauns', definition: 'Rebotar' },
    { word: 'Breathe', pronunciation: 'bruid', definition: 'Respirar' },
    { word: 'Brush', pronunciation: 'brach', definition: 'Cepillar' },
    { word: 'Burn', pronunciation: 'bern', definition: 'Quemar' },
    { word: 'Bury', pronunciation: '', definition: 'Enterrar' },

    { word: 'Calculate', pronunciation: 'kalkiu-leit', definition: 'Calcular' },
    { word: 'Call', pronunciation: 'col', definition: 'Llamar' },
    { word: 'Calm', pronunciation: 'calm', definition: 'Calmar - Calma' },
    { word: 'Camp', pronunciation: 'camp', definition: 'Acampar - Campamento' },
    { word: 'Cancel', pronunciation: 'ken-sol', definition: 'Cancelar' },
    { word: 'Capture', pronunciation: 'cap-cher', definition: 'Capturar - Captura' },
    { word: 'Care', pronunciation: 'ker', definition: 'Cuidar - Cuidado' },
    { word: 'Carry', pronunciation: 'kerrui', definition: 'Llevar - Portar' },
    { word: 'Cause', pronunciation: 'kas', definition: 'Causar - Causa - Caso' },
    { word: 'Celebrate', pronunciation: 'sele-breit', definition: 'Celebrar' },
    { word: 'Challenge', pronunciation: 'chalench', definition: 'Desafiar' },
    { word: 'Change', pronunciation: 'cheinch', definition: 'Cambiar' },
    { word: 'Charge', pronunciation: 'charch', definition: 'Cargar' },
    { word: 'Chase', pronunciation: 'cheis', definition: 'Perseguir' },
    { word: 'Check', pronunciation: 'chek', definition: 'Revisar' },
    { word: 'Cheer', pronunciation: 'chir', definition: 'Animar - Alegría' },
    { word: 'Claim', pronunciation: 'cleim', definition: 'Reclamar' },
    { word: 'Clarify', pronunciation: 'cleri-fai', definition: 'Aclarar' },
    { word: 'Clean', pronunciation: 'clin', definition: 'Limpiar - Limpio' },
    { word: 'Clear ', pronunciation: 'clir', definition: 'Despejar - Limpio - despejado' },
    { word: 'Climb ', pronunciation: 'claim', definition: 'Escalar - Trepar' },
    { word: 'Close', pronunciation: 'clous', definition: 'Cerrar' },
    { word: 'Collect', pronunciation: 'colect', definition: 'Recolectar - Recoger' },
    { word: 'Comment', pronunciation: 'coument', definition: 'Comentar - Comentario' },
    { word: 'Communicate', pronunciation: 'comiuni-keit', definition: 'Comunicarse - Comunicar' },
    { word: 'Compare', pronunciation: 'comper', definition: 'Comparar' },
    { word: 'Compete', pronunciation: 'compit', definition: 'Competir' },
    { word: 'Complain', pronunciation: 'com-plein', definition: 'Quejarse - Queja' },
    { word: 'Complete', pronunciation: 'com-plit', definition: 'Completar' },
    { word: 'Concentrate', pronunciation: 'cansen-trueit', definition: 'Concentrarse' },
    { word: 'Conclude', pronunciation: 'ken-klud', definition: 'Concluir' },
    { word: 'Confess', pronunciation: 'ken-fes', definition: 'Confesar' },
    { word: 'Confirm', pronunciation: 'ken-ferm', definition: 'Confirmar' },
    { word: 'Connect', pronunciation: 'ke-nect', definition: 'Conectar' },
    { word: 'Conserve', pronunciation: 'ken-serv', definition: 'Conservar' },
    { word: 'Consider', pronunciation: 'ken-sider', definition: 'Considerar' },
    { word: 'Consist', pronunciation: 'ken-sist', definition: 'Consistir' },
    { word: 'Construct', pronunciation: 'kenstroct', definition: 'Construir' },
    { word: 'Consult', pronunciation: 'ken-sel', definition: 'Consultar' },
    { word: 'Contain', pronunciation: 'ken-tein', definition: 'Contener' },
    { word: 'Continue', pronunciation: 'ken-tiniu', definition: 'Continuar' },
    { word: 'Contribute', pronunciation: 'ken-truebiut', definition: 'Contribuir' },
    { word: 'Convert', pronunciation: 'ken-vert', definition: 'Convertir' },
    { word: 'Cook', pronunciation: 'kuc', definition: 'Cocinar' },
    { word: 'Cooperate', pronunciation: 'kou-opereit', definition: 'Cooperar' },
    { word: 'Copy', pronunciation: 'copi', definition: 'Copiar' },
    { word: 'Correct', pronunciation: 'kerrect', definition: 'Corregir - Correcto' },
    { word: 'Cost', pronunciation: 'cost', definition: 'Costar - Costo' },
    { word: 'Counsel', pronunciation: 'kaun-sol', definition: 'Aconsejar - Consejo' },
    { word: 'Count', pronunciation: 'kaunt', definition: 'Contar' },
    { word: 'Cover', pronunciation: 'cover', definition: 'Cubrir' },
    { word: 'Crawl', pronunciation: 'crol', definition: 'Arrastrarse' },
    { word: 'Create', pronunciation: 'crieit', definition: 'Crear' },
    { word: 'Cross', pronunciation: 'cros', definition: 'Cruzar - Cruz' },
    { word: 'Cry', pronunciation: 'krai', definition: 'Llorar' },

    { word: 'Damage', pronunciation: 'dameich', definition: 'Dañar - Daño' },
    { word: 'Dance', pronunciation: 'dans', definition: 'Bailar - Danza' },
    { word: 'Dare', pronunciation: 'der', definition: 'Atreverse - Atrevimiento - Desafiar' },
    { word: 'Date', pronunciation: 'deit', definition: 'Citar - Cita - Fecha' },
    { word: 'Discuss', pronunciation: 'des-cas', definition: 'Conversar - Debatir' },
    { word: 'Decide', pronunciation: 'desaid', definition: 'Decidir' },
    { word: 'Declare', pronunciation: 'de-cler', definition: 'Declarar' },
    { word: 'Decline', pronunciation: 'di-clain', definition: 'Rechazar - Declinar - Disminución' },
    { word: 'Decorate', pronunciation: 'decoreit', definition: 'Decorar' },
    { word: 'Decrease', pronunciation: 'de-kruis', definition: 'Disminuir' },
    { word: 'Dehydrate', pronunciation: 'dijai-dreit', definition: 'Deshidratar' },
    { word: 'Delay', pronunciation: 'delei', definition: 'Retrasar - Posponer - Retraso' },
    { word: 'Delete', pronunciation: 'delit', definition: 'Eliminar' },
    { word: 'Deliver', pronunciation: 'deliver', definition: 'Entregar' },
    { word: 'Demand', pronunciation: 'demand', definition: 'Demandar - Demanda' },
    { word: 'Demonstrate', pronunciation: 'demenstreit', definition: 'Demostrar' },
    { word: 'Depend', pronunciation: 'dipend', definition: 'Depender' },
    { word: 'Deploy', pronunciation: 'deploy', definition: 'Desplegar' },
    { word: 'Describe', pronunciation: 'des-craib', definition: 'Describir' },
    { word: 'Design', pronunciation: 'desain', definition: 'Diseñar - Diseño' },
    { word: 'Desire', pronunciation: 'desaier', definition: 'Desear - Deseo' },
    { word: 'Destroy', pronunciation: 'distroy', definition: 'Destruir' },
    { word: 'Detect', pronunciation: 'detect', definition: 'Detectar' },
    { word: 'Develop', pronunciation: 'develep', definition: 'Desarrollar' },
    { word: 'Dictate', pronunciation: 'dicteit', definition: 'Dictar' },
    { word: 'Die', pronunciation: 'dai', definition: 'Morir' },
    { word: 'Direct', pronunciation: '', definition: 'Dirigir - Directo' },
    { word: 'Disagree', pronunciation: 'dise-gri', definition: 'No estar de acuerdo' },
    { word: 'Disappear', pronunciation: 'disapir', definition: 'Desaparecer' },
    { word: 'Discover', pronunciation: 'deskaver', definition: 'Descubrir' },
    { word: 'Discuss', pronunciation: 'deskas', definition: 'Conversar - Discutir' },
    { word: 'Distribute', pronunciation: 'destribiut', definition: 'Distribuir' },
    { word: 'Distribute', pronunciation: 'destribiut', definition: 'Distribuir' },
    { word: 'Distribute', pronunciation: 'destribiut', definition: 'Distribuir' },
    { word: 'Distribute', pronunciation: 'destribiut', definition: 'Distribuir' },
    { word: 'Dispose', pronunciation: 'dispos', definition: 'Disponer - Colocar - Resolver' },
    { word: 'Distribute', pronunciation: 'destribiut', definition: 'Distribuir' },
    { word: 'Dive', pronunciation: 'daiv', definition: 'Bucear - Sumergirse' },
    { word: 'Divide', pronunciation: 'devaid', definition: 'Dividir' },
    { word: 'Donate', pronunciation: 'doneit', definition: 'Donar' },
    { word: 'Doubt', pronunciation: 'dout', definition: 'Dudar - Duda' },
    { word: 'Download', pronunciation: 'daun-loud', definition: 'Dudar - Duda' },
    { word: 'Dream', pronunciation: 'dru-im', definition: 'Soñar - Sueño' },
    { word: 'Dress', pronunciation: 'dru-es', definition: 'Vertirse - Vestido - Vestir' },
    { word: 'Drill', pronunciation: 'druil', definition: 'Perforar' },
    { word: 'Drop', pronunciation: 'drop', definition: 'Dejar caer - caida - descenso - Gota' },
    { word: 'Dry', pronunciation: 'dray', definition: 'Secar - Seco' },

    { word: 'Earn', pronunciation: 'ern', definition: 'Obtener - Ganar' },

    { word: 'FIlter', pronunciation: 'filter', definition: 'Filtrar' },
    { word: 'Fix', pronunciation: 'fix', definition: 'Reparar' },

    { word: 'Guide', pronunciation: 'gaid', definition: 'Guiar - Guía' },

    { word: 'Handle', pronunciation: 'jendel', definition: 'Manejar - Controlar' },
    { word: 'Heat', pronunciation: 'jit', definition: 'Calentar - Calor' },
    { word: 'Hunt', pronunciation: 'jant', definition: 'Cazar - Caza' },
    { word: 'Hydrate', pronunciation: 'jai-drueit', definition: 'Hidratar' },

    { word: 'Improve', pronunciation: 'impruf', definition: 'Mejorar' },
    { word: 'Increase', pronunciation: 'incruis', definition: 'Aumentar - Aumento' },

    { word: 'Learn', pronunciation: 'lern', definition: 'Aprender' },
    { word: 'Like', pronunciation: 'laik', definition: 'Gustar - Como' },

    { word: 'Manage', pronunciation: 'menech', definition: 'Manejar - Administrar' },
    { word: 'Merge', pronunciation: 'merch', definition: 'unir' },

    { word: 'Open', pronunciation: 'open', definition: 'Abrir - Abierto' },
    { word: 'Organize', pronunciation: 'organais', definition: 'Organizar' },

    { word: 'Penetrate', pronunciation: 'penetreit', definition: 'Penetrar' },
    { word: 'Plan', pronunciation: 'plan', definition: 'Planear - Plan' },
    { word: 'Plant', pronunciation: 'plant', definition: 'Plantar - Planta' },
    { word: 'Play', pronunciation: 'pley', definition: 'Jugar - Reproducir' },
    { word: 'Poison', pronunciation: 'poisen', definition: 'Envenenar - Veneno' },
    { word: 'Present', pronunciation: 'present', definition: 'Presentar' },
    { word: 'Press', pronunciation: 'pres', definition: 'Presionar - Prensa' },
    { word: 'Print', pronunciation: 'print', definition: 'Imprimir - Impresión' },
    { word: 'Program', pronunciation: 'prou-gram', definition: 'Programar - Programa' },
    { word: 'Promise', pronunciation: 'promes', definition: 'Prometer - Promesa' },
    { word: 'Protect', pronunciation: 'pro-tect', definition: 'Proteger' },
    { word: 'Provide', pronunciation: 'provaid', definition: 'Proporcionar - Proveer' },
    { word: 'Purify', pronunciation: 'piure-fay', definition: 'Purificar' },

    { word: 'Recover', pronunciation: 'ruecover', definition: 'Recuperar' },
    { word: 'Report', pronunciation: 'rueport', definition: 'Reportar - Reporte' },
    { word: 'Rescue', pronunciation: 'rues-kiu', definition: 'Rescatar - Rescate' },
    { word: 'Return', pronunciation: 'rue-tern', definition: 'Devolver' },

    { word: 'Save', pronunciation: 'seif', definition: 'Salvar - Guardar - Ahorrar' },
    { word: 'Search', pronunciation: 'serch', definition: 'Buscar - Búsqueda' },
    { word: 'Seem', pronunciation: 'sim', definition: 'Parecer' },
    { word: 'Share', pronunciation: 'cher', definition: 'Compartir' },
    { word: 'Shave', pronunciation: 'sheiv', definition: 'Afeitar' },
    { word: 'Smell', pronunciation: 'smel', definition: 'Oler' },
    { word: 'Spell', pronunciation: 'spell', definition: 'Deletrear - Hechizo' },
    { word: 'Spend', pronunciation: 'spend', definition: 'Gastar' },
    { word: 'Spill', pronunciation: 'spil', definition: 'Derramar' },
    { word: 'Start', pronunciation: 'start', definition: 'Comenzar' },
    { word: 'Stop', pronunciation: 'stap', definition: 'Detenerse' },
    { word: 'Study', pronunciation: 'stady', definition: 'Estudiar' },
    { word: 'Support', pronunciation: 'se-port', definition: 'Apoyar - Financiar - Apoyo' },
    { word: 'Survive', pronunciation: 'servaiv', definition: 'Sobrevivir' },

    { word: 'Test', pronunciation: 'test', definition: 'Probar - Prueba' },
    { word: 'Tie', pronunciation: 'tai', definition: 'Atar - Corbata - Empate' },
    { word: 'Travel', pronunciation: 'truavol', definition: 'Viajar - Viaje' },

    { word: 'Use', pronunciation: 'ius', definition: 'Usar - Uso' },

    { word: 'Walk', pronunciation: 'uok', definition: 'Caminar - Caminata' },
    { word: 'Warn', pronunciation: 'uorn', definition: 'Advertir' },
    { word: 'Whistle', pronunciation: 'uisel', definition: 'Silbar - Silbato' },
];
const irregularVerbs = [
    { word: 'Arise', pronunciation: '', definition: 'Levantarse - Surgir' },

    { word: 'Be', pronunciation: 'bi', definition: 'Ser - Estar' },
    { word: 'Become', pronunciation: 'bicom', definition: 'Convertirse' },
    { word: 'Begin', pronunciation: 'biguin', definition: 'Comenzar' },
    { word: 'Bend', pronunciation: 'bend', definition: 'Doblar' },
    { word: 'Bet', pronunciation: 'bet', definition: 'Apostar - Apuesta' },
    { word: 'Bite', pronunciation: 'bait', definition: 'Morder - Mordedura' },
    { word: 'Beat', pronunciation: 'bit', definition: 'Derrotar' },
    { word: 'Bleed', pronunciation: 'blid', definition: 'Sangrar' },
    { word: 'Blow', pronunciation: 'blou', definition: 'Soplar' },
    { word: 'Break', pronunciation: 'breik', definition: 'Romper - Quebrar - Pausa' },
    { word: 'Breed', pronunciation: 'brid', definition: 'Criar - Raza' },
    { word: 'Bring', pronunciation: 'bring', definition: 'Traer' },
    { word: 'Build', pronunciation: 'bild', definition: 'Construir' },
    { word: 'Buy', pronunciation: 'bay', definition: 'Comprar' },

    { word: 'Catch', pronunciation: 'catch', definition: 'Atrapar' },
    { word: 'Choose', pronunciation: 'chus', definition: 'Elegir' },
    { word: 'Cling', pronunciation: 'cling', definition: 'Aferrarse' },
    { word: 'Come', pronunciation: 'com', definition: 'Venir' },
    { word: 'Cost', pronunciation: 'cost', definition: 'Costar - Costo' },
    { word: 'Cut', pronunciation: 'cot', definition: 'Cortar - Corte' },

    { word: 'Deal', pronunciation: 'dil', definition: 'Negociar - Trato' },
    { word: 'Dig', pronunciation: 'dig', definition: 'Cavar - Excavar' },
    { word: 'Do', pronunciation: 'du', definition: 'Hacer' },
    { word: 'Draw', pronunciation: 'drou', definition: 'Dibujar' },
    { word: 'Drink', pronunciation: 'druink', definition: 'Beber' },
    { word: 'Drive', pronunciation: 'druaiv', definition: 'Conducir' },
    { word: 'Dwell', pronunciation: 'druell', definition: 'Habitar - Morar' },

    { word: 'Eat', pronunciation: 'it', definition: 'Comer' },

    { word: 'Fall', pronunciation: 'fol', definition: 'Caer' },
    { word: 'Feed', pronunciation: 'fid', definition: 'Alimentarse' },
    { word: 'Feel', pronunciation: 'fil', definition: 'Sentir' },
    { word: 'Fight', pronunciation: 'fait', definition: 'Pelear' },
    { word: 'Find', pronunciation: 'faind', definition: 'Encontrar' },
    { word: 'Flee', pronunciation: 'fli', definition: 'Huir' },

];
const phrasalVerbs = [
    { word: 'Bring back', pronunciation: 'bruinc bac', definition: 'Devolver' },

    { word: 'Come back', pronunciation: 'com bak', definition: 'Regresar' },

    { word: 'Find out', pronunciation: 'faind aut', definition: 'Descubrir - Averiguar' },
    { word: 'Figure out', pronunciation: 'figuiur aut', definition: 'Resolver - Entender' },

    { word: 'Go out', pronunciation: 'gou aut', definition: 'Salir - Dejar de funcionar' },
    { word: 'Give up', pronunciation: 'giv up', definition: 'Rendirse - dejar' },
    { word: 'Get up', pronunciation: 'get ap', definition: 'Levantarse' },
    { word: 'Get up', pronunciation: 'get ap', definition: 'Levantarse' },
    { word: 'Go over', pronunciation: 'gou over', definition: 'Revisar - Repasar' },
    { word: 'Go through', pronunciation: 'gou tru', definition: 'Atravesar - Pasar' },

    { word: 'Wake up', pronunciation: 'ueik ap', definition: 'Despertarse' },

    { word: 'Look up', pronunciation: 'luc ap', definition: 'Mirar hacia arriba' },
    { word: 'Look for', pronunciation: 'luc for', definition: 'Buscar' },

    { word: 'Pick up', pronunciation: 'pic ap', definition: 'Recoger - Levantar' },
    { word: 'Put on', pronunciation: 'put on', definition: 'Vestirse - Aplicarse' },

    { word: 'Run into', pronunciation: 'ruan into', definition: 'Encontrarse con algo/alguien' },

    { word: 'Turn on', pronunciation: 'torn on', definition: 'Encender' },
    { word: 'Turn off', pronunciation: 'torn of', definition: 'Apagar' },
    { word: 'Take off', pronunciation: 'teik of', definition: 'Despegar - Quitarse' },
    { word: 'Throw away', pronunciation: 'tru euey', definition: 'Tirar - Deshacerse' },


];
const verbToBe = [
    { word: 'am', pronunciation: 'am', definition: 'Ser' },
    { word: 'Is', pronunciation: 'is', definition: 'Ser' },
    { word: 'Are', pronunciation: 'arr', definition: 'Ser' },
];
const auxiliarVerbs = [
    { word: 'Can', pronunciation: 'can', definition: 'Poder' },
    { word: 'Could', pronunciation: 'cud', definition: 'Podría' },
    { word: 'Will', pronunciation: 'uill', definition: 'Verbo auxiliar futuro' },
    { word: 'Would', pronunciation: 'wud', definition: '' },
    { word: 'Should', pronunciation: 'shud', definition: 'Debería' },
    { word: 'May', pronunciation: 'mey', definition: 'Puede' },
    { word: 'Might', pronunciation: 'mait', definition: 'Podría' },
    { word: 'Must', pronunciation: 'most', definition: 'Debe' },
];

const findWord = regularVerbs.map((element) => {
    return element.word.toLowerCase();
})

const FindRepeatedWords = () => {

    var word = 'center';
    let repeatedPosition;

    const repeatedWord = findWord.filter((element) => {
        return element === word.toLowerCase();
    });

    console.log(repeatedWord);

    if (repeatedWord.length > 1) {
        repeatedPosition = findWord.indexOf(word)
    } else {
        repeatedPosition = null;
    }
    console.log(`¿Does the word exist? ${findWord.includes(word)}`);

    console.log(`Repeated position: ${repeatedPosition}`);
}

// FindRepeatedWords();

// console.log(`Number of words: ${findWord.length}`);


export { words, regularVerbs, irregularVerbs, phrasalVerbs, verbToBe, auxiliarVerbs };











